# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('likes', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='FlightPriceCache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelCache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('json_value', models.CharField(max_length=200000)),
            ],
        ),
        migrations.CreateModel(
            name='HotelPriceCache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_data', models.CharField(max_length=15000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakaton.Customer')),
            ],
        ),
    ]
