# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('likes', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_data', models.CharField(max_length=15000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hakaton.Customer')),
            ],
        ),
    ]
