# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakaton', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelCache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('json_value', models.CharField(max_length=200000)),
            ],
        ),
    ]
